name = "QuartoNotebookRunner"
uuid = "4c0109c6-14e9-4c88-93f0-2b974d3468f4"
authors = ["Michael Hatherly <michael@pumas.ai>", "Julius Krumbiegel <juliusk@pumas.ai>"]
version = "0.17.4"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
BSON = "0.3"
Base64 = "1.6"
CommonMark = "0.8, 0.9"
Compat = "4"
Dates = "1.6"
IOCapture = "0.2"
InteractiveUtils = "1.6"
IterTools = "1"
JSON3 = "1"
Logging = "1.6"
Pkg = "1.6"
PrecompileTools = "1"
Preferences = "1"
ProgressLogging = "0.1.4"
REPL = "1.6"
Random = "1.6"
RelocatableFolders = "1"
SHA = "0.7, 1"
Sockets = "1.6"
TOML = "1"
YAML = "0.4"
julia = "1.6"
